version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: sith4-api-test

