version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: sith4-api-test
  api:
    platform: linux/amd64
    container_name: api
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./config/config.override.yml
        target: /usr/src/app/dist
