version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - api-ae-db-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: sith4-api-test
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  mailhog:
    container_name: mailhog 
    image: dockage/mailcatcher:latest
    ports:
      - 1080:1080
      - 1025:1025
volumes:
  api-ae-db-data:
    driver: local