# Default config file for api
# !!!!! This file serves as an exemple config file BUT ALSO as the test environment. Edit it with precaution
#
# To customize configuration :
# - Copy this file and rename it config.override.yml
# - Edit the desired property
# - Restart the server

# Server configuration
http:
  host: 'localhost'
  port: 3000

# Database configuration
db:
  engine: 'postgresql'
  host: 'test-db'
  port: 5432
  user: 'test'
  password: 'test'
  name: 'sith4-api-test'
  args: 'schema=public'

auth:
  jwt-secret: 'test-secret'
